;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((emacs-lisp-mode . ((nameless-aliases . (("cc" . "chronometrist-common")
                                          ("cd" . "chronometrist-details")
                                          ("ce" . "chronometrist-events")
                                          ("ck" . "chronometrist-key-values")
                                          ("cm" . "chronometrist-migrate")
                                          ("cp" . "chronometrist-plist-pp")
                                          ("cr" . "chronometrist-report")
                                          ("cs" . "chronometrist-statistics")
                                          ("cx" . "chronometrist-sexp")
                                          ("c" . "chronometrist")))
                     (outline-regexp . ";;;+ ")))
 (org-mode . ((nameless-aliases . (("cc" . "chronometrist-common")
                                   ("cd" . "chronometrist-details")
                                   ("ce" . "chronometrist-events")
                                   ("ck" . "chronometrist-key-values")
                                   ("cm" . "chronometrist-migrate")
                                   ("cp" . "chronometrist-plist-pp")
                                   ("cr" . "chronometrist-report")
                                   ("cs" . "chronometrist-statistics")
                                   ("cx" . "chronometrist-sexp")
                                   ("c" . "chronometrist")))
              (org-html-self-link-headlines . t)
              (eval . (org-indent-mode)))))
